[0m[[0m[31merror[0m] [0m[0morg.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"[0m
[0m[[0m[31merror[0m] [0m[0m	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:623)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:163)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:215)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.postgresql.Driver.makeConnection(Driver.java:466)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.postgresql.Driver.connect(Driver.java:265)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)[0m
[0m[[0m[31merror[0m] [0m[0m	at Connector.getConnection(Connector.scala:11)[0m
[0m[[0m[31merror[0m] [0m[0m	at Main$.main(Main.scala:16)[0m
[0m[[0m[31merror[0m] [0m[0m	at Main.main(Main.scala)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.reflect.Method.invoke(Method.java:566)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.invokeMain(Run.scala:143)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.execute$1(Run.scala:93)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run$.executeSuccess(Run.scala:186)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.runWithLoader(Run.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$bgRunMainTask$7(Defaults.scala:1948)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1919)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.util.Try$.apply(Try.scala:213)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:366)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:834)[0m
[0m[[0m[31merror[0m] [0m[0m(Compile / [31mrunMain[0m) org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"[0m
